<?php

namespace App;

use App\Business\MongoEloquentModel as Model;
use App\Business\Repositories\ProductRepository;
use App\Exceptions\OutOfStockException;

class Order extends Model
{

    const New = 1;
    const ValidData = 2;
    const ToRedirect = 3;
    const Redirected = 4;
    const Confirmed = 5;
    const Cancelled = -1;
    const Error = -2;

    protected $fillable = [
        'billing_id', 'shipping_id', 'user_id', 'status', 'payment_method', 'external_id'
    ];

    public $attributes = [
        'status' => Order::New
    ];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::creating(function($order) {
            /** @var Order $order */
            $order->cart()->map(function ($cart) {
                /** @var Variation $variation */
                $variation = (new ProductRepository())->findBy('_id', $cart->product_id)
                    ->productVariation(array_merge([$cart->product_id], $cart->properties));

                if($variation->stock - $cart->quantity < 0 ) {
                    throw new OutOfStockException(trans('exceptions.out_of_stock', ['product' => $variation->name]));
                }
            });
        });
    }

    /**
     * @return \Jenssegers\Mongodb\Relations\EmbedsOne
     */
    public function billing()
    {
        return $this->embedsOne(Billing::class);
    }

    /**
     * @return \Jenssegers\Mongodb\Relations\EmbedsOne
     */
    public function shipping()
    {
        return $this->embedsOne(Shipping::class);
    }

    /**
     * @return \Jenssegers\Mongodb\Relations\EmbedsMany
     */
    public function cart()
    {
        return $this->embedsMany(Cart::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function buyer()
    {
        return $this->belongsTo(Buyer::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function payment_method()
    {
        return $this->belongsTo(PaymentMethod::class);
    }

    /**
     * @return bool
     */
    public static function isCurrentOrderConfirmed()
    {
        $order = self::currentOrder();
        return !$order->isEmpty() && $order->first()->status == self::Confirmed ? true : false;
    }

    /**
     * @return Order|null
     */
    public static function currentOrder() {
        return self::where('token', \Request::session()->get('order'))->get();
    }

    public function conditionsFilter($condition)
    {
        return collect($this->conditions)
            ->filter(function($conditions) use ($condition) {
                return $conditions['type'] == $condition;
            })->first();
    }
}
